[
  {
    "_id": 123,
    "topic": "Space",
    "userName": "SpaceX",
    "title": "Tesla Cybertruck lands on Mars and picks up the Curiosity rover on its 6' bed",
    "time": "4h",
    "image": "https://image.cnbcfm.com/api/v1/image/107118394-1663162493777-SpaceX-1568010239185944576-img1.jpg?v=1668704401",
    "liked": true,
    "replies": "123",
    "retuits": "432",
    "likes": "245",
    "handle": "@spacex",
    "disliked":false,
    "dislikes":30,
    "tuit": "SpaceX release enjoy!!.HTML and CSS on their own can create compelling static Web pages.We'll write JavaScript code that can react to user events, can generate dynamic HTML, and modify the DOM programmatically."
  },
  {
    "_id": 234,
    "topic": "Space",
    "userName": "SpaceX",
    "title": "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
    "time": "Yesterday",
    "image": "https://cdn.mos.cms.futurecdn.net/Rrfa4oEWQHekzXPW7K58fj.jpg",
    "liked": false,
    "replies": "123",
    "retuits": "4",
    "likes": "986",
    "handle": "@web",
    "disliked":true,
    "dislikes":40,
    "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars"
  },
  {
    "_id": 345,
    "topic": "Energy",
    "userName": "Tesla",
    "title": "Tesla FSD finally makes driving obsolete. After years of delay, Tesla Full Self Driving can drive you to work while you work, play, or sleep",
    "time": "4d",
    "image": "https://electrek.co/wp-content/uploads/sites/3/2021/05/Tesla-Logo-Hero.jpg?quality=82&strip=all&w=1600",
    "liked": true,
    "replies": "23",
    "retuits": "96",
    "likes": "2300",
    "handle": "@tesla",
    "disliked":false,
    "dislikes":20,
    "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars"
  }
]